### ISSUE TITLE
Unalbe to import pagination_params

### ISSUE THREAD

**Issue by shyamsukhamit** [uriyyo/fastapi-pagination#34]
Earlier when I have installed fastapi-pagination it was 0.5.2 it was working fine

Today I  installed then the version is .0.6.1

now it produces following error.
 
 
from fastapi_pagination import pagination_params
ImportError: cannot import name 'pagination_params' from 'fastapi_pagination' 

when I am trying to import :

from fastapi_pagination import pagination_params
from fastapi_pagination.paginator import paginate
from fastapi_pagination import PaginationParams, Page

Same code is working fine in 0.5.2

Any help is appreciated.

**Comment by uriyyo** [comment]
Hi @shyamsukhamit,

The API has been changed. There are no`pagination_params` no more.

Example:
```python
from fastapi import FastAPI
from pydantic import BaseModel

from fastapi_pagination import Page, add_pagination, paginate

app = FastAPI()


class User(BaseModel):
    name: str
    surname: str


users = [
    User(name='Yurii', surname='Karabas'),
    # ...
]


@app.get('/users', response_model=Page[User])
async def get_users():
    return paginate(users)


add_pagination(app)
```

**Comment by uriyyo** [comment]
I will return `pagination_params` in version `0.7.0` but it will be marked as deprecated

**Comment by shyamsukhamit** [comment]
Hi, Can you please help - how to pass custom per page size i.e. Limit  in the below code? I tried but no success


@router.get("/", response_model=Page[schemas.Table1B])
@router.get("/limit-offset", response_model=LimitOffsetPage[schemas.Table1B])
def get_table(db: Session = Depends(get_db),skip: int = 0, limit: int = 2) -> Any:
    return paginate(db.query(models.Table1))

**Comment by uriyyo** [comment]
Version `0.7.0` has been released.

There are `with_custom_options` class method that allows set custom values for params:

For instance:
```py
@router.get(
    "/limit-offset",
    response_model=LimitOffsetPage.with_custom_options(limit=2, offset=0)[schemas.Table1B],
)
def get_table(db: Session = Depends(get_db)) -> Any:
    return paginate(db.query(models.Table1))
```

**Comment by shyamsukhamit** [comment]
Please forgive my ignorance  but that does'nt seem to work - it returns full set of records

Am I missing anything.

```

@router.get("/", response_model=Page[schemas.Table1B])
@router.get("/limit-offset", response_model=LimitOffsetPage.with_custom_options(limit=2, offset=0)[schemas.Table1B],)
def get_table(db: Session = Depends(get_db)) -> Any:
    return paginate(db.query(models.Table1))
```

**Comment by uriyyo** [comment]
@shyamsukhamit Could you please provide more context on how to reproduce this issue?

I have just double-checked and everything works as expected:
![image](https://user-images.githubusercontent.com/32038156/111269424-4d1cfa00-8637-11eb-9dab-ecde4e0d0806.png)

**Comment by shyamsukhamit** [comment]
my bad - I was executing the router get("/"), request did not notice the limit-offset router - when I access the .get("/limit-offset") then it provides the pagination.

Thank you so much for the help.

**Comment by uriyyo** [comment]
Your welcome, I am closing this issue, in case if it appears again feel free to reopen this issue.
